services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-net

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/user_db
    depends_on:
      - postgres
    networks:
      - microservices-net

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/product_db
    depends_on:
      - postgres
    networks:
      - microservices-net

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/order_db
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - postgres
      - user-service
      - product-service
    networks:
      - microservices-net

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: